# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e56d6110ee5567f790e3ad301538039a40657a0f379cdc84410260e4ae46d4a9974262f9f7420348ed842dfa9b2aa3b2fa21e3b45b93e42e714469bb9c8c106

test:
  secret_key_base: 97481f02c445773486856320d07ccac12bcdb2a1f7f337d19c72dbba9286ce961da21e063e782867d59566c64153bdadd5fd20f88970fbd341a5a5743262bb8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
